In [1]:
#Numpy is Numerical Python and support for creating and manipulating arrays.

In [ ]:
'''
Uses of Numpy  1. Arthamatic Operations
               2. Statistical Opearations
               3. BitWise Operators
               4. Copying & Viewing Operations
               5. Stackig
               6. Searching,Sorting,Counting
               7. MatheMatical Operations
               8. Bradcasting
               9. LinerAlgebra
               10.Matrix Operations '''

In [3]:
# anaconda prompt ---> pip install numpy ----> to install numpy 
or
# anaconda prompt ----> conda insstall numpy  ---> to install numpy 

In [76]:
import numpy as np # To Import Numpy Library 

In [77]:
print(np.__version__)  #To check what version using numpy

1.23.5


## Creating Arrays

In [6]:
lt = [10,20,30,40,50]  #List
lt

[10, 20, 30, 40, 50]

In [7]:
arr = np.array(lt) # To convert list into array
arr

array([10, 20, 30, 40, 50])

In [8]:
np.arange(10) #Create the array by defalt value is 0 and here stop value is 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5) #Create the array by defalt value is 0 and here stop value is 5

array([0, 1, 2, 3, 4])

In [10]:
np.arange(0,6) #Create the array by starting value is 0 and here stop value is 6

array([0, 1, 2, 3, 4, 5])

In [11]:
np.arange(5,10) #Create the array by starting value is 5 and here stop value is 10

array([5, 6, 7, 8, 9])

In [12]:
np.arange(2,8,2) # Starting value is 2, Stoping Value is 8, & step value is 2

array([2, 4, 6])

In [18]:
np.arange(2,8,2, dtype= float) # Starting value is 2, Stoping Value is 8, & step value is 2
                                 #with float values

array([2., 4., 6.])

In [16]:
np.arange(2,8,2, dtype= bool)  # Boolean Data Types are not allowed to creating arrays 

ValueError: no fill-function for data-type.

In [19]:
np.arange(2,8,2, dtype= complex) # Starting value is 2, Stoping Value is 8, & step value is 2
                                 #with Complex values

array([2.+0.j, 4.+0.j, 6.+0.j])

In [21]:
  np.zeros(10)  # Single Array with by default it is float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype = int)# Singlr Array with Int data type


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros((2,5),) # Creating 2-D array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros((2,5), dtype = int) # Creating 2-D array with Int Data Type

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.ones((2,2), dtype = complex)

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [28]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])

In [29]:
np.twos((2,2)) # Twos Functin not supported in Numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [108]:
np.linspace(3,15,num=10)

array([ 3.        ,  4.33333333,  5.66666667,  7.        ,  8.33333333,
        9.66666667, 11.        , 12.33333333, 13.66666667, 15.        ])

In [80]:
np.linspace(2,10,num = 5) #Create an array with evenly spaced values over a specified range.
                          # By Default End Point is True

array([ 2.,  4.,  6.,  8., 10.])

In [82]:
np.linspace(2,10,num=5, endpoint =False)

array([2. , 3.6, 5.2, 6.8, 8.4])

In [84]:
np.linspace(2,20,num=5, endpoint =True, dtype = int)

array([ 2,  6, 11, 15, 20])

In [85]:
np.full(3,5)

array([5, 5, 5])

In [86]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [92]:
np.full((3,3,3),5, dtype = complex)

array([[[5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j]],

       [[5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j]],

       [[5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j],
        [5.+0.j, 5.+0.j, 5.+0.j]]])

In [94]:
np.full((3,3,3),5, dtype = bool)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [104]:
np.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 8.69555537e-321, 6.23057348e-307, 1.42419530e-306])

In [105]:
empty_array = np.empty((3, 3))
print(empty_array)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.83389375e-321]
 [6.23057348e-307 1.42419530e-306 4.24399158e-314]]


In [109]:
np.identity(3) # This will give Identity Matrix & m=n that means we can pass only one argument

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
np.eye(3,4)  # This will give Identity Matrix & m!=n that means we can pass only two argument

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [106]:
lt = [[1,2,3],[4,5,6],[7,8,9]]
np.array(lt)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
#Create an array with ranging 9,49 with both are inclusive
np.linspace(9,49, num=9, endpoint= True, dtype = int)

array([ 9, 14, 19, 24, 29, 34, 39, 44, 49])

In [124]:
#Create the an Identity Matrix in size 5*6 with integer
np.eye(5,6, dtype = int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [127]:
#Given length of rope is 5m, we cut at 9parts, each part is equal length
np.linspace (0,5, num=9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

## Array Operations 

In [30]:
np.random.randint(10) #Uniformly distributed integers in up to 10

8

In [116]:
np.random.randint(10, size= (4,4))

array([[4, 7, 4, 9],
       [4, 1, 0, 2],
       [3, 8, 0, 1],
       [6, 0, 8, 6]])

In [31]:
np.random.randint(0,3) # give result with random number between 0 & 3 & Starting Value must be low 

2

In [119]:
np.random.randint(-22,10, size = (3,4)) # give result with random number between -22 & 10 with size 3*4

array([[ -4, -12,   8,  -6],
       [  3,  -2,   0,   1],
       [ -1, -13,   3,   9]])

In [43]:
np.random.randint(0,10,5)  # 0 Means Starting Value
                           #10 Means Stoping Value
                           # 5 is Generated values (5 Times)

array([9, 1, 6, 9, 0])

In [34]:
np.random.randint(-5,5,5)

array([-2,  3,  4,  3,  3])

In [35]:
np.random.randn() # Generate a random number from the standard normal distribution

-0.2508024926464925

In [36]:
np.random.randn(5)  # Generate a 1D array with 5 random numbers from the standard normal distribution

array([ 0.83688872,  1.17406866, -0.31515413,  0.22147328, -0.2962892 ])

In [37]:
np.random.randn(3,4) # Generate a 2D array

array([[-0.36940387, -0.29867285,  1.05623243, -0.34088172],
       [-0.74961806,  0.07688412,  2.46828526,  0.54450569],
       [-1.67592603, -1.11381572,  0.63426351, -0.05118654]])

In [38]:
np.random.randn(3,4,5) # 3D Array with 3 layers each containing 4 rows and 5 columns

array([[[-6.76658681e-01, -8.90792010e-01,  1.53963763e+00,
          1.02751828e+00, -1.32914990e+00],
        [-2.03632852e+00,  6.72271985e-01, -1.43041804e+00,
         -1.61746320e-01, -1.64764967e+00],
        [-1.55380616e+00,  6.41838339e-01,  1.00069376e+00,
         -7.39747632e-01,  2.97469183e+00],
        [ 1.75921134e-01,  9.54618161e-01, -1.79846445e+00,
         -1.63361636e+00, -1.07289012e+00]],

       [[ 1.56380558e+00,  1.14521843e-01, -3.82310853e-01,
         -2.38434823e-03,  1.69957952e+00],
        [-6.97259750e-02, -1.20684595e+00,  9.64576006e-01,
          9.51767750e-01, -1.14360761e+00],
        [ 9.20789179e-01, -8.35593988e-01,  6.63271710e-01,
          4.70314821e-01, -6.13278754e-01],
        [-1.69589149e+00,  4.16034175e-01,  1.31004852e-01,
         -6.71284298e-01, -3.07654377e-01]],

       [[-6.18842241e-01, -1.34026381e+00,  9.49259601e-01,
          1.06950565e+00,  1.87526865e-02],
        [ 1.15754985e+00, -6.38274356e-01, -6.09806666e-01,


In [39]:
np.random.rand(5) # 1D array 

array([0.73255292, 0.06731164, 0.64981561, 0.28049438, 0.10062725])

In [40]:
np.random.rand(2,5) # 2D Array

array([[0.41532373, 0.3142634 , 0.07479389, 0.98065487, 0.3343449 ],
       [0.8611418 , 0.97407179, 0.22704867, 0.54892511, 0.83195331]])

In [41]:
np.random.rand(2,2,3) # 3D Array with 2 layers each containing 2 rows and 3 columns

array([[[0.50233581, 0.26541708, 0.97708938],
        [0.45131147, 0.44481097, 0.94302521]],

       [[0.98423708, 0.68423609, 0.51491049],
        [0.10749146, 0.72545695, 0.16124221]]])

In [ ]:
'''The Difference b/n Randn & Rand is 
Randn = This function generates random numbers from a standard normal distribution 
        The values produced have a mean of 0 and a standard deviation of 1.
        
Rand = This function generates random numbers from a uniform distribution over the interval (0, 1).
'''

In [53]:
np.random.random(5) # 1D Array with Size 5

array([0.24002801, 0.6913727 , 0.35275994, 0.70760973, 0.81941767])

In [64]:
np.random.random((2,5)) # 2D Array & result only float values

array([[0.002759  , 0.53119514, 0.84078206, 0.04728047, 0.24646876],
       [0.75253001, 0.12314179, 0.00088448, 0.07162881, 0.54424561]])

In [69]:
arr = np.random.random((2,5,4)) # 3D Array with 2 Layers, 5 Rows and 4 Coloumns
print (arr)
print(type(arr))

[[[0.20228555 0.25738978 0.74934048 0.97199212]
  [0.22627407 0.04365892 0.53019815 0.3008533 ]
  [0.43659956 0.23398537 0.13573563 0.39068808]
  [0.1644458  0.83295125 0.69136198 0.92805259]
  [0.33068931 0.62127962 0.92623842 0.91038236]]

 [[0.43436414 0.90246424 0.4469489  0.59348996]
  [0.59897465 0.96765731 0.55393292 0.34911989]
  [0.56712727 0.04237251 0.76466069 0.78968179]
  [0.70875497 0.45402081 0.22295723 0.69581681]
  [0.35034565 0.34556836 0.32049208 0.86768715]]]
<class 'numpy.ndarray'>


In [66]:
np.random.random(0)

array([], dtype=float64)

In [67]:
np.random.random((0,0))

array([], shape=(0, 0), dtype=float64)

## Indexing & Slicing

In [1]:
li_2d =[ [10,20,30], [40,50,60],[70,80,90],[100,110,120]]
li_2d

[[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]]

In [6]:
import numpy as np
arr_2d = np.array(li_2d)
arr_2d

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [7]:
arr_2d[-4,-3]

10

In [8]:
arr_2d[3,2]

120

In [13]:
arr = np.arange(0,100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
# Required Number is 55
arr [5,5]

55

In [17]:
# Required Number is 34
arr[3,4]

34

In [18]:
# Required Number is 48
arr[4,8]

48

In [19]:
# Required Number is 72
arr[7,2]

72

In [20]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
# Required Number is 95
arr[9,5]

95

In [22]:
# Required Number is 12
arr[1,2]

12

In [23]:
# Required Number is 25
arr[2,5]

25

In [24]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
# Required Number is 1 with Negative Indexing
arr[-10,-9]

1

In [27]:
# Required Number is 80 with Negative Indexing
arr[-2,-10]

80

In [30]:
# Required Number is 62 with Negative Indexing
arr[-4,-8]

62

In [31]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
row = 5
col = 6

In [37]:
arr[ row, col]

56

In [38]:
arr [ : , col] # it gives result entire 6th coloumn

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [39]:
arr[6] # it gives result entire 6th row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [40]:
arr [ 5 , :]  #it gives result entire 5th row

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
arr[ 4 , 1 :6 ] #4th Row with column 1 to 5th index(n-1)

array([41, 42, 43, 44, 45])

In [43]:
# Print 42,52,62,72
arr [ 4:8 ,2]

array([42, 52, 62, 72])

In [44]:
# Print 14,15,16,17 & 24,25,26,27
arr [1:3,4:8]

array([[14, 15, 16, 17],
       [24, 25, 26, 27]])

In [45]:
#Print [42,43,44], [ 52,53,54],[62,63,64]
arr [4:7,2:5]

array([[42, 43, 44],
       [52, 53, 54],
       [62, 63, 64]])

## Mathematical Operations
Max | min  | mean  | sum  | median

In [46]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
arr.sum()

4950

In [48]:
arr.min ()

0

In [49]:
arr.max ()

99

In [50]:
arr.mean()

49.5

In [51]:
arr.median ()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [58]:
a = np.random.randint(0,9, size =(3,3))
a

array([[7, 7, 8],
       [4, 8, 6],
       [3, 6, 6]])

In [60]:
b = np.random.randint(9,20, size = (3,3))
b

array([[19,  9,  9],
       [12, 11, 14],
       [10, 11,  9]])

In [62]:
c = a+b
c

array([[26, 16, 17],
       [16, 19, 20],
       [13, 17, 15]])

In [63]:
d = b-a
d

array([[12,  2,  1],
       [ 8,  3,  8],
       [ 7,  5,  3]])

## Masking 

In [ ]:
# Masking is alos known as Filter

In [64]:
arr >50  # only give result above 50 are True remaining False

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [66]:
arr >= 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [67]:
arr !=40 #Only 40 will became false remaining True

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [68]:
arr [arr>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
arr [ arr!=40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Reshape

In [72]:
arr_2d

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [74]:
aa =np.random.randint(0,4, size =(3,2))
aa

array([[1, 2],
       [3, 0],
       [3, 3]])

In [75]:
aa.reshape(2,3)

array([[1, 2, 3],
       [0, 3, 3]])